### ISSUE TITLE
scrolling by click-and-drag doesn't work in Firefox

### ISSUE THREAD

**Issue by sonyaa** [CSE512-15S/a3-jbare-sonyaa-tws10#14]
Works fine in Chrome, but on Firefox I got this:
![bug](https://cloud.githubusercontent.com/assets/6108821/7443474/60f535f0-f101-11e4-9184-7f0e9feeaaab.png)

**Comment by tschmidt23** [comment]
oops...

**Comment by tschmidt23** [comment]
closed with 709591e32689619adf0ef8878f05778647f151b0

although it is really slow on firefox
