### ISSUE TITLE
make justice view appear on the side

### ISSUE THREAD

**Issue by sonyaa** [CSE512-15S/a3-jbare-sonyaa-tws10#15]
Since monitors are usually wider than taller, it'd make more sense for the two views to appear side-by-side, not top-to-bottom.

**Comment by sonyaa** [comment]
Tanner - I've assigned you since you know this stuff way better than me, but feel free to reassign to Justin or me if you've got more important stuff to work on.

**Comment by jbare** [comment]
I moved the justice view to the side, but I had some trouble with moving the radio button form and decided to go to bed instead

**Comment by sonyaa** [comment]
smart decision! probably that's what I should do too

**Comment by sonyaa** [comment]
I think currently it's impossible to put the form in the right place because both charts are part of the same svg. They should probably be separate svgs in the same div.

**Comment by tschmidt23** [comment]
Where exactly do we want it to go?

**Comment by sonyaa** [comment]
If the views are side-by-side, the controls/legend should probably be below so as not to take up any more width. I don't know about the filters for the main view, though, those should probably be in the middle (are we actually implementing them? if not, then the justice view should be closer to the main view - currently there's a big gap between them).

**Comment by tschmidt23** [comment]
ok - right now the gap is to accommodate the labels for justices on the side. should we just put those over the justice view then?

**Comment by sonyaa** [comment]
Ooh, I see. Maybe? I don't know...

**Comment by sonyaa** [comment]
Maybe just squeeze everything a little? Make all parts a little narrower. It's just that on a smaller screen (14") the views don't fit in: 
![screenshot from 2015-05-03 19 36 59](https://cloud.githubusercontent.com/assets/6108821/7448337/002868c0-f1cc-11e4-8734-d7a7da1f9ea4.png)

(On a related note: since the justice view cannot be turned off after it appears for the first time, maybe it should appear together with the main view? For the first displayed justice. Otherwise at first the main view looks lonely and too small for the whole screen.)

**Comment by sonyaa** [comment]
Opened #23 for this problem
