### ISSUE TITLE
create map from justice ID to human-readable justice name.

### ISSUE THREAD

**Issue by tschmidt23** [CSE512-15S/a3-jbare-sonyaa-tws10#2]
Probably something along the lines of:

<code>
var justiceNamesFriendly = { 78: "Hugo Black", ... };
</code>

This may be a helpful resource:

http://en.wikipedia.org/wiki/List_of_Justices_of_the_Supreme_Court_of_the_United_States#Graphic_timeline

**Comment by sonyaa** [comment]
closed with 8ca553a

**Comment by tschmidt23** [comment]
awesome
